<a href="https://colab.research.google.com/github/samruddhi1902/Python/blob/main/numpy_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.identity(4)

In [ ]:
data=np.array([1, 2, 3, 4])
data.ndim
data.shape
data


array([1, 2, 3, 4])

In [ ]:
x1 = 5.4 * np.ones(10)
x1
x2 = np.full(10, 5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.diag(np.arange(0,20,5)) #a-range

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [ ]:
np.diag([10, 20, 30, 40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [ ]:
a = np.array(range(11))

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[0]

0

In [ ]:
a[-1]

10

In [ ]:
a[-2]

9

In [ ]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
a[5:-2]

array([5, 6, 7, 8])

In [ ]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
a[-5: 0]

array([], dtype=int64)

In [ ]:
a[-5:0:-1]

array([6, 5, 4, 3, 2, 1])

In [ ]:
f = lambda m, n: n+10*m
A = np.fromfunction(f, (6,6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
A[:, 1] # second column; slicing + integer indexing

array([ 1, 11, 21, 31, 41, 51])

In [ ]:
A[1,:] # second row

array([10, 11, 12, 13, 14, 15])

In [ ]:
A[:3, :3] # slicing + slicing

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
A[3:, :3] # slicing + slicing

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [ ]:
A[-1, -1]

55

In [ ]:
A[::-1]

array([[50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45],
       [30, 31, 32, 33, 34, 35],
       [20, 21, 22, 23, 24, 25],
       [10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5]])

In [ ]:
A[::-1,::-1]

array([[55, 54, 53, 52, 51, 50],
       [45, 44, 43, 42, 41, 40],
       [35, 34, 33, 32, 31, 30],
       [25, 24, 23, 22, 21, 20],
       [15, 14, 13, 12, 11, 10],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
A[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [ ]:
A[-1]

array([50, 51, 52, 53, 54, 55])

In [ ]:
A[2]

array([20, 21, 22, 23, 24, 25])

In [ ]:
A[1::2,1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

In [ ]:
# View
B = A[1:5, 1:5] # Object is same!!
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [ ]:
B[:,:] = 0 #changes to B changes A as well
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
# To copy an array/subarray, you have to use .copy(). It creates a new object
C = B[1:3,1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [ ]:
C[:,:] = 1 # since its a copy, a view is not created
B, C

(array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1, 1],
        [1, 1]]))

In [ ]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])